In [7]:
import os
import png
import pydicom as dicom
import argparse
import numpy as np
import cv2

def mri_to_png(mri_file, png_file):
    """ Function to convert from a DICOM image to png
        @param mri_file: An opened file like object to read te dicom data
        @param png_file: An opened file like object to write the png data
    """

    # Extracting data from the mri file
    plan = dicom.read_file(mri_file)
    shape = plan.pixel_array.shape

    image_2d = []
    max_val = 0
    for row in plan.pixel_array:
        pixels = []
        for col in row:
            pixels.append(col)
            if col > max_val: max_val = col
        image_2d.append(pixels)

    # Rescaling grey scale between 0-255
    image_2d_scaled = []
    for row in image_2d:
        row_scaled = []
        for col in row:
            col_scaled = int((float(col) / float(max_val)) * 255.0)
            row_scaled.append(col_scaled)
        image_2d_scaled.append(row_scaled)

    # Writing the PNG file
    w = png.Writer(shape[1], shape[0], greyscale=True)
    display(np.histogram(image_2d_scaled))
    w.write(png_file, image_2d_scaled)


def convert_file(mri_file_path, png_file_path):
    """ Function to convert an MRI binary file to a
        PNG image file.
        @param mri_file_path: Full path to the mri file
        @param png_file_path: Fill path to the png file
    """

    # Making sure that the mri file exists
    if not os.path.exists(mri_file_path):
        raise Exception('File "%s" does not exists' % mri_file_path)

    # Making sure the png file does not exist
    if os.path.exists(png_file_path):
        raise Exception('File "%s" already exists' % png_file_path)

    mri_file = open(mri_file_path, 'rb')
    png_file = open(png_file_path, 'wb')

    mri_to_png(mri_file, png_file)

    png_file.close()


def convert_folder(mri_folder, png_folder):
    """ Convert all MRI files in a folder to png files
        in a destination folder
    """

    # Create the folder for the pnd directory structure
    if not os.path.exists(png_folder):
        os.makedirs(png_folder)

    # Recursively traverse all sub-folders in the path
    for mri_sub_folder, subdirs, files in os.walk(mri_folder):
        for mri_file in os.listdir(mri_sub_folder):
            mri_file_path = os.path.join(mri_sub_folder, mri_file)

            # Make sure path is an actual file
            if os.path.isfile(mri_file_path):

                # Replicate the original file structure
                rel_path = os.path.relpath(mri_sub_folder, mri_folder)
                png_folder_path = os.path.join(png_folder, rel_path)
                if not os.path.exists(png_folder_path):
                    os.makedirs(png_folder_path)
                png_file_path = os.path.join(png_folder_path, '%s.png' % mri_file.replace(".dcm",""))

                try:
                    # Convert the actual file
                    convert_file(mri_file_path, png_file_path)
                    print('SUCCESS>', mri_file_path, '-->', png_file_path)
                except Exception as e:
                    print('FAIL>', mri_file_path, '-->', png_file_path, ':', e)


# if __name__ == '__main__':
#     parser = argparse.ArgumentParser(description="Convert a dicom MRI file to png")
#     parser.add_argument('-f', action='store_true')
#     parser.add_argument('dicom_path', help='Full path to the mri file')
#     parser.add_argument('png_path', help='Full path to the generated png file')

#     args = parser.parse_args()
#     print args
#     if args.f:
#         convert_folder(args.dicom_path, args.png_path)
#     else:
#         convert_file(args.dicom_path, args.png_path)


In [8]:
dicom_path="D:\\datasets\\lung\\ild\\ILD_DB_lungMasksK\\101\\"
png_path="D:\\datasets\\lung\\ild\\ILD_DB_lungMasksKPNG\\101\\"
convert_folder(dicom_path, png_path)

(array([55772,     0,     0, 43414, 81157, 39779, 39187,  2340,   424,
           71], dtype=int64),
 array([-166. , -123.9,  -81.8,  -39.7,    2.4,   44.5,   86.6,  128.7,
         170.8,  212.9,  255. ]))

FAIL> D:\datasets\lung\ild\ILD_DB_lungMasksK\101\CT-0002-0001.dcm --> D:\datasets\lung\ild\ILD_DB_lungMasksKPNG\101\.\CT-0002-0001.png : byte must be in range(0, 256)


(array([ 55772,      0,      0, 101872,  15869,  71238,  15122,   1811,
           433,     27], dtype=int64),
 array([-155., -114.,  -73.,  -32.,    9.,   50.,   91.,  132.,  173.,
         214.,  255.]))

FAIL> D:\datasets\lung\ild\ILD_DB_lungMasksK\101\CT-0002-0002.dcm --> D:\datasets\lung\ild\ILD_DB_lungMasksKPNG\101\.\CT-0002-0002.png : byte must be in range(0, 256)


(array([55772,     0,     0, 76912, 38153, 58921, 29330,  2285,   682,
           89], dtype=int64),
 array([-162. , -120.3,  -78.6,  -36.9,    4.8,   46.5,   88.2,  129.9,
         171.6,  213.3,  255. ]))

FAIL> D:\datasets\lung\ild\ILD_DB_lungMasksK\101\CT-0002-0003.dcm --> D:\datasets\lung\ild\ILD_DB_lungMasksKPNG\101\.\CT-0002-0003.png : byte must be in range(0, 256)


(array([55772,     0,     0, 98881, 17084, 73501, 14472,  1782,   584,
           68], dtype=int64),
 array([-156. , -114.9,  -73.8,  -32.7,    8.4,   49.5,   90.6,  131.7,
         172.8,  213.9,  255. ]))

FAIL> D:\datasets\lung\ild\ILD_DB_lungMasksK\101\CT-0002-0004.dcm --> D:\datasets\lung\ild\ILD_DB_lungMasksKPNG\101\.\CT-0002-0004.png : byte must be in range(0, 256)


(array([ 55772,      0,      0, 105076,  15949,  75857,   7665,   1305,
           461,     59], dtype=int64),
 array([-154. , -113.1,  -72.2,  -31.3,    9.6,   50.5,   91.4,  132.3,
         173.2,  214.1,  255. ]))

FAIL> D:\datasets\lung\ild\ILD_DB_lungMasksK\101\CT-0002-0005.dcm --> D:\datasets\lung\ild\ILD_DB_lungMasksKPNG\101\.\CT-0002-0005.png : byte must be in range(0, 256)


(array([55772,     0,     0, 71023, 47415, 52406, 32719,  1989,   674,
          146], dtype=int64),
 array([-164. , -122.1,  -80.2,  -38.3,    3.6,   45.5,   87.4,  129.3,
         171.2,  213.1,  255. ]))

FAIL> D:\datasets\lung\ild\ILD_DB_lungMasksK\101\CT-0002-0006.dcm --> D:\datasets\lung\ild\ILD_DB_lungMasksKPNG\101\.\CT-0002-0006.png : byte must be in range(0, 256)


(array([ 55772,      0,      0,      0, 116605,  21653,  64735,   2731,
           482,    166], dtype=int64),
 array([-174. , -131.1,  -88.2,  -45.3,   -2.4,   40.5,   83.4,  126.3,
         169.2,  212.1,  255. ]))

FAIL> D:\datasets\lung\ild\ILD_DB_lungMasksK\101\CT-0002-0007.dcm --> D:\datasets\lung\ild\ILD_DB_lungMasksKPNG\101\.\CT-0002-0007.png : byte must be in range(0, 256)


(array([55772,     0,     0, 54450, 68497, 43211, 37594,  1948,   553,
          119], dtype=int64),
 array([-165., -123.,  -81.,  -39.,    3.,   45.,   87.,  129.,  171.,
         213.,  255.]))

FAIL> D:\datasets\lung\ild\ILD_DB_lungMasksK\101\CT-0002-0008.dcm --> D:\datasets\lung\ild\ILD_DB_lungMasksKPNG\101\.\CT-0002-0008.png : byte must be in range(0, 256)


(array([55772,     0,     0, 50624, 72873, 42667, 37687,  1858,   517,
          146], dtype=int64),
 array([-166. , -123.9,  -81.8,  -39.7,    2.4,   44.5,   86.6,  128.7,
         170.8,  212.9,  255. ]))

FAIL> D:\datasets\lung\ild\ILD_DB_lungMasksK\101\CT-0002-0009.dcm --> D:\datasets\lung\ild\ILD_DB_lungMasksKPNG\101\.\CT-0002-0009.png : byte must be in range(0, 256)


(array([ 55772,      0,      0,      0, 114951,  24659,  63552,   2593,
           501,    116], dtype=int64),
 array([-176. , -132.9,  -89.8,  -46.7,   -3.6,   39.5,   82.6,  125.7,
         168.8,  211.9,  255. ]))

FAIL> D:\datasets\lung\ild\ILD_DB_lungMasksK\101\CT-0002-0010.dcm --> D:\datasets\lung\ild\ILD_DB_lungMasksKPNG\101\.\CT-0002-0010.png : byte must be in range(0, 256)


(array([55772,     0,     0, 35790, 82406, 37951, 47660,  2445,   113,
            7], dtype=int64),
 array([-168. , -125.7,  -83.4,  -41.1,    1.2,   43.5,   85.8,  128.1,
         170.4,  212.7,  255. ]))

FAIL> D:\datasets\lung\ild\ILD_DB_lungMasksK\101\CT-0002-0011.dcm --> D:\datasets\lung\ild\ILD_DB_lungMasksKPNG\101\.\CT-0002-0011.png : byte must be in range(0, 256)


(array([55772,     0,     0, 88839, 30665, 73052, 12760,   815,   201,
           40], dtype=int64),
 array([-158. , -116.7,  -75.4,  -34.1,    7.2,   48.5,   89.8,  131.1,
         172.4,  213.7,  255. ]))

FAIL> D:\datasets\lung\ild\ILD_DB_lungMasksK\101\CT-0002-0012.dcm --> D:\datasets\lung\ild\ILD_DB_lungMasksKPNG\101\.\CT-0002-0012.png : byte must be in range(0, 256)


(array([55772,     0,     0, 91579, 31632, 71820,  9857,  1080,   382,
           22], dtype=int64),
 array([-156. , -114.9,  -73.8,  -32.7,    8.4,   49.5,   90.6,  131.7,
         172.8,  213.9,  255. ]))

FAIL> D:\datasets\lung\ild\ILD_DB_lungMasksK\101\CT-0002-0013.dcm --> D:\datasets\lung\ild\ILD_DB_lungMasksKPNG\101\.\CT-0002-0013.png : byte must be in range(0, 256)


(array([55772,     0,     0, 50661, 71029, 48675, 34002,  1588,   363,
           54], dtype=int64),
 array([-166. , -123.9,  -81.8,  -39.7,    2.4,   44.5,   86.6,  128.7,
         170.8,  212.9,  255. ]))

FAIL> D:\datasets\lung\ild\ILD_DB_lungMasksK\101\CT-0002-0014.dcm --> D:\datasets\lung\ild\ILD_DB_lungMasksKPNG\101\.\CT-0002-0014.png : byte must be in range(0, 256)


(array([55772,     0,     0, 86762, 35160, 70177, 13038,   962,   220,
           53], dtype=int64),
 array([-159. , -117.6,  -76.2,  -34.8,    6.6,   48. ,   89.4,  130.8,
         172.2,  213.6,  255. ]))

FAIL> D:\datasets\lung\ild\ILD_DB_lungMasksK\101\CT-0002-0015.dcm --> D:\datasets\lung\ild\ILD_DB_lungMasksKPNG\101\.\CT-0002-0015.png : byte must be in range(0, 256)


(array([55772,     0,     0, 83864, 46702, 63140, 11312,  1054,   262,
           38], dtype=int64),
 array([-159. , -117.6,  -76.2,  -34.8,    6.6,   48. ,   89.4,  130.8,
         172.2,  213.6,  255. ]))

FAIL> D:\datasets\lung\ild\ILD_DB_lungMasksK\101\CT-0002-0016.dcm --> D:\datasets\lung\ild\ILD_DB_lungMasksKPNG\101\.\CT-0002-0016.png : byte must be in range(0, 256)


(array([ 55772,      0,      0,      0, 115647,  24286,  64098,   2134,
           186,     21], dtype=int64),
 array([-177. , -133.8,  -90.6,  -47.4,   -4.2,   39. ,   82.2,  125.4,
         168.6,  211.8,  255. ]))

FAIL> D:\datasets\lung\ild\ILD_DB_lungMasksK\101\CT-0002-0017.dcm --> D:\datasets\lung\ild\ILD_DB_lungMasksKPNG\101\.\CT-0002-0017.png : byte must be in range(0, 256)


(array([ 55772,      0,      0, 100206,  25353,  75654,   4533,    527,
            94,      5], dtype=int64),
 array([-148. , -107.7,  -67.4,  -27.1,   13.2,   53.5,   93.8,  134.1,
         174.4,  214.7,  255. ]))

FAIL> D:\datasets\lung\ild\ILD_DB_lungMasksK\101\CT-0002-0018.dcm --> D:\datasets\lung\ild\ILD_DB_lungMasksKPNG\101\.\CT-0002-0018.png : byte must be in range(0, 256)


(array([ 55772,      0,      0,      0, 116068,  20748,  66099,   2980,
           390,     87], dtype=int64),
 array([-183. , -139.2,  -95.4,  -51.6,   -7.8,   36. ,   79.8,  123.6,
         167.4,  211.2,  255. ]))

FAIL> D:\datasets\lung\ild\ILD_DB_lungMasksK\101\CT-0002-0019.dcm --> D:\datasets\lung\ild\ILD_DB_lungMasksKPNG\101\.\CT-0002-0019.png : byte must be in range(0, 256)


(array([ 55772,      0,      0,      0, 116108,  26411,  61536,   1990,
           285,     42], dtype=int64),
 array([-174. , -131.1,  -88.2,  -45.3,   -2.4,   40.5,   83.4,  126.3,
         169.2,  212.1,  255. ]))

FAIL> D:\datasets\lung\ild\ILD_DB_lungMasksK\101\CT-0002-0020.dcm --> D:\datasets\lung\ild\ILD_DB_lungMasksKPNG\101\.\CT-0002-0020.png : byte must be in range(0, 256)


(array([ 55772,      0,      0,      0, 100605,  12256,  86571,   6391,
           512,     37], dtype=int64),
 array([-198. , -152.7, -107.4,  -62.1,  -16.8,   28.5,   73.8,  119.1,
         164.4,  209.7,  255. ]))

FAIL> D:\datasets\lung\ild\ILD_DB_lungMasksK\101\CT-0002-0021.dcm --> D:\datasets\lung\ild\ILD_DB_lungMasksKPNG\101\.\CT-0002-0021.png : byte must be in range(0, 256)


(array([ 55772,      0,      0,      0, 105501,  19347,  79404,   1815,
           268,     37], dtype=int64),
 array([-173. , -130.2,  -87.4,  -44.6,   -1.8,   41. ,   83.8,  126.6,
         169.4,  212.2,  255. ]))

FAIL> D:\datasets\lung\ild\ILD_DB_lungMasksK\101\CT-0002-0022.dcm --> D:\datasets\lung\ild\ILD_DB_lungMasksKPNG\101\.\CT-0002-0022.png : byte must be in range(0, 256)


(array([ 55772,      0,      0,      0, 103146,   6776,  93373,   2765,
           247,     65], dtype=int64),
 array([-182. , -138.3,  -94.6,  -50.9,   -7.2,   36.5,   80.2,  123.9,
         167.6,  211.3,  255. ]))

FAIL> D:\datasets\lung\ild\ILD_DB_lungMasksK\101\CT-0002-0023.dcm --> D:\datasets\lung\ild\ILD_DB_lungMasksKPNG\101\.\CT-0002-0023.png : byte must be in range(0, 256)


(array([ 55772,      0,      0,      0, 102938,   3722,  95212,   3986,
           440,     74], dtype=int64),
 array([-192. , -147.3, -102.6,  -57.9,  -13.2,   31.5,   76.2,  120.9,
         165.6,  210.3,  255. ]))

FAIL> D:\datasets\lung\ild\ILD_DB_lungMasksK\101\CT-0002-0024.dcm --> D:\datasets\lung\ild\ILD_DB_lungMasksKPNG\101\.\CT-0002-0024.png : byte must be in range(0, 256)
FAIL> D:\datasets\lung\ild\ILD_DB_lungMasksK\101\ff.png --> D:\datasets\lung\ild\ILD_DB_lungMasksKPNG\101\.\ff.png.png : File is missing DICOM File Meta Information header or the 'DICM' prefix is missing from the header. Use force=True to force reading.


(array([261959,      0,      0,      0,      0,      0,      0,      0,
             0,    185], dtype=int64),
 array([  0. ,  25.5,  51. ,  76.5, 102. , 127.5, 153. , 178.5, 204. ,
        229.5, 255. ]))

SUCCESS> D:\datasets\lung\ild\ILD_DB_lungMasksK\101\lung_mask\lung_mask_2_1.dcm --> D:\datasets\lung\ild\ILD_DB_lungMasksKPNG\101\lung_mask\lung_mask_2_1.png


(array([229244,      0,      0,      0,      0,      0,      0,      0,
             0,  32900], dtype=int64),
 array([  0. ,  25.5,  51. ,  76.5, 102. , 127.5, 153. , 178.5, 204. ,
        229.5, 255. ]))

SUCCESS> D:\datasets\lung\ild\ILD_DB_lungMasksK\101\lung_mask\lung_mask_2_10.dcm --> D:\datasets\lung\ild\ILD_DB_lungMasksKPNG\101\lung_mask\lung_mask_2_10.png


(array([230311,      0,      0,      0,      0,      0,      0,      0,
             0,  31833], dtype=int64),
 array([  0. ,  25.5,  51. ,  76.5, 102. , 127.5, 153. , 178.5, 204. ,
        229.5, 255. ]))

SUCCESS> D:\datasets\lung\ild\ILD_DB_lungMasksK\101\lung_mask\lung_mask_2_11.dcm --> D:\datasets\lung\ild\ILD_DB_lungMasksKPNG\101\lung_mask\lung_mask_2_11.png


(array([232238,      0,      0,      0,      0,      0,      0,      0,
             0,  29906], dtype=int64),
 array([  0. ,  25.5,  51. ,  76.5, 102. , 127.5, 153. , 178.5, 204. ,
        229.5, 255. ]))

SUCCESS> D:\datasets\lung\ild\ILD_DB_lungMasksK\101\lung_mask\lung_mask_2_12.dcm --> D:\datasets\lung\ild\ILD_DB_lungMasksKPNG\101\lung_mask\lung_mask_2_12.png


(array([225368,      0,      0,      0,      0,      0,      0,      0,
             0,  36776], dtype=int64),
 array([  0. ,  25.5,  51. ,  76.5, 102. , 127.5, 153. , 178.5, 204. ,
        229.5, 255. ]))

SUCCESS> D:\datasets\lung\ild\ILD_DB_lungMasksK\101\lung_mask\lung_mask_2_13.dcm --> D:\datasets\lung\ild\ILD_DB_lungMasksKPNG\101\lung_mask\lung_mask_2_13.png


(array([224436,      0,      0,      0,      0,      0,      0,      0,
             0,  37708], dtype=int64),
 array([  0. ,  25.5,  51. ,  76.5, 102. , 127.5, 153. , 178.5, 204. ,
        229.5, 255. ]))

SUCCESS> D:\datasets\lung\ild\ILD_DB_lungMasksK\101\lung_mask\lung_mask_2_14.dcm --> D:\datasets\lung\ild\ILD_DB_lungMasksKPNG\101\lung_mask\lung_mask_2_14.png


(array([227436,      0,      0,      0,      0,      0,      0,      0,
             0,  34708], dtype=int64),
 array([  0. ,  25.5,  51. ,  76.5, 102. , 127.5, 153. , 178.5, 204. ,
        229.5, 255. ]))

SUCCESS> D:\datasets\lung\ild\ILD_DB_lungMasksK\101\lung_mask\lung_mask_2_15.dcm --> D:\datasets\lung\ild\ILD_DB_lungMasksKPNG\101\lung_mask\lung_mask_2_15.png


(array([217402,      0,      0,      0,      0,      0,      0,      0,
             0,  44742], dtype=int64),
 array([  0. ,  25.5,  51. ,  76.5, 102. , 127.5, 153. , 178.5, 204. ,
        229.5, 255. ]))

SUCCESS> D:\datasets\lung\ild\ILD_DB_lungMasksK\101\lung_mask\lung_mask_2_16.dcm --> D:\datasets\lung\ild\ILD_DB_lungMasksKPNG\101\lung_mask\lung_mask_2_16.png


(array([225502,      0,      0,      0,      0,      0,      0,      0,
             0,  36642], dtype=int64),
 array([  0. ,  25.5,  51. ,  76.5, 102. , 127.5, 153. , 178.5, 204. ,
        229.5, 255. ]))

SUCCESS> D:\datasets\lung\ild\ILD_DB_lungMasksK\101\lung_mask\lung_mask_2_17.dcm --> D:\datasets\lung\ild\ILD_DB_lungMasksKPNG\101\lung_mask\lung_mask_2_17.png


(array([231753,      0,      0,      0,      0,      0,      0,      0,
             0,  30391], dtype=int64),
 array([  0. ,  25.5,  51. ,  76.5, 102. , 127.5, 153. , 178.5, 204. ,
        229.5, 255. ]))

SUCCESS> D:\datasets\lung\ild\ILD_DB_lungMasksK\101\lung_mask\lung_mask_2_18.dcm --> D:\datasets\lung\ild\ILD_DB_lungMasksKPNG\101\lung_mask\lung_mask_2_18.png


(array([226690,      0,      0,      0,      0,      0,      0,      0,
             0,  35454], dtype=int64),
 array([  0. ,  25.5,  51. ,  76.5, 102. , 127.5, 153. , 178.5, 204. ,
        229.5, 255. ]))

SUCCESS> D:\datasets\lung\ild\ILD_DB_lungMasksK\101\lung_mask\lung_mask_2_19.dcm --> D:\datasets\lung\ild\ILD_DB_lungMasksKPNG\101\lung_mask\lung_mask_2_19.png


(array([261835,      0,      0,      0,      0,      0,      0,      0,
             0,    309], dtype=int64),
 array([  0. ,  25.5,  51. ,  76.5, 102. , 127.5, 153. , 178.5, 204. ,
        229.5, 255. ]))

SUCCESS> D:\datasets\lung\ild\ILD_DB_lungMasksK\101\lung_mask\lung_mask_2_2.dcm --> D:\datasets\lung\ild\ILD_DB_lungMasksKPNG\101\lung_mask\lung_mask_2_2.png


(array([228812,      0,      0,      0,      0,      0,      0,      0,
             0,  33332], dtype=int64),
 array([  0. ,  25.5,  51. ,  76.5, 102. , 127.5, 153. , 178.5, 204. ,
        229.5, 255. ]))

SUCCESS> D:\datasets\lung\ild\ILD_DB_lungMasksK\101\lung_mask\lung_mask_2_20.dcm --> D:\datasets\lung\ild\ILD_DB_lungMasksKPNG\101\lung_mask\lung_mask_2_20.png


(array([254948,      0,      0,      0,      0,      0,      0,      0,
             0,   7196], dtype=int64),
 array([  0. ,  25.5,  51. ,  76.5, 102. , 127.5, 153. , 178.5, 204. ,
        229.5, 255. ]))

SUCCESS> D:\datasets\lung\ild\ILD_DB_lungMasksK\101\lung_mask\lung_mask_2_21.dcm --> D:\datasets\lung\ild\ILD_DB_lungMasksKPNG\101\lung_mask\lung_mask_2_21.png


(array([258715,      0,      0,      0,      0,      0,      0,      0,
             0,   3429], dtype=int64),
 array([  0. ,  25.5,  51. ,  76.5, 102. , 127.5, 153. , 178.5, 204. ,
        229.5, 255. ]))

SUCCESS> D:\datasets\lung\ild\ILD_DB_lungMasksK\101\lung_mask\lung_mask_2_22.dcm --> D:\datasets\lung\ild\ILD_DB_lungMasksKPNG\101\lung_mask\lung_mask_2_22.png


(array([260990,      0,      0,      0,      0,      0,      0,      0,
             0,   1154], dtype=int64),
 array([  0. ,  25.5,  51. ,  76.5, 102. , 127.5, 153. , 178.5, 204. ,
        229.5, 255. ]))

SUCCESS> D:\datasets\lung\ild\ILD_DB_lungMasksK\101\lung_mask\lung_mask_2_23.dcm --> D:\datasets\lung\ild\ILD_DB_lungMasksKPNG\101\lung_mask\lung_mask_2_23.png


(array([261964,      0,      0,      0,      0,      0,      0,      0,
             0,    180], dtype=int64),
 array([  0. ,  25.5,  51. ,  76.5, 102. , 127.5, 153. , 178.5, 204. ,
        229.5, 255. ]))

SUCCESS> D:\datasets\lung\ild\ILD_DB_lungMasksK\101\lung_mask\lung_mask_2_24.dcm --> D:\datasets\lung\ild\ILD_DB_lungMasksKPNG\101\lung_mask\lung_mask_2_24.png


(array([260245,      0,      0,      0,      0,      0,      0,      0,
             0,   1899], dtype=int64),
 array([  0. ,  25.5,  51. ,  76.5, 102. , 127.5, 153. , 178.5, 204. ,
        229.5, 255. ]))

SUCCESS> D:\datasets\lung\ild\ILD_DB_lungMasksK\101\lung_mask\lung_mask_2_3.dcm --> D:\datasets\lung\ild\ILD_DB_lungMasksKPNG\101\lung_mask\lung_mask_2_3.png


(array([255868,      0,      0,      0,      0,      0,      0,      0,
             0,   6276], dtype=int64),
 array([  0. ,  25.5,  51. ,  76.5, 102. , 127.5, 153. , 178.5, 204. ,
        229.5, 255. ]))

SUCCESS> D:\datasets\lung\ild\ILD_DB_lungMasksK\101\lung_mask\lung_mask_2_4.dcm --> D:\datasets\lung\ild\ILD_DB_lungMasksKPNG\101\lung_mask\lung_mask_2_4.png


(array([248541,      0,      0,      0,      0,      0,      0,      0,
             0,  13603], dtype=int64),
 array([  0. ,  25.5,  51. ,  76.5, 102. , 127.5, 153. , 178.5, 204. ,
        229.5, 255. ]))

SUCCESS> D:\datasets\lung\ild\ILD_DB_lungMasksK\101\lung_mask\lung_mask_2_5.dcm --> D:\datasets\lung\ild\ILD_DB_lungMasksKPNG\101\lung_mask\lung_mask_2_5.png


(array([245319,      0,      0,      0,      0,      0,      0,      0,
             0,  16825], dtype=int64),
 array([  0. ,  25.5,  51. ,  76.5, 102. , 127.5, 153. , 178.5, 204. ,
        229.5, 255. ]))

SUCCESS> D:\datasets\lung\ild\ILD_DB_lungMasksK\101\lung_mask\lung_mask_2_6.dcm --> D:\datasets\lung\ild\ILD_DB_lungMasksKPNG\101\lung_mask\lung_mask_2_6.png


(array([239168,      0,      0,      0,      0,      0,      0,      0,
             0,  22976], dtype=int64),
 array([  0. ,  25.5,  51. ,  76.5, 102. , 127.5, 153. , 178.5, 204. ,
        229.5, 255. ]))

SUCCESS> D:\datasets\lung\ild\ILD_DB_lungMasksK\101\lung_mask\lung_mask_2_7.dcm --> D:\datasets\lung\ild\ILD_DB_lungMasksKPNG\101\lung_mask\lung_mask_2_7.png


(array([232178,      0,      0,      0,      0,      0,      0,      0,
             0,  29966], dtype=int64),
 array([  0. ,  25.5,  51. ,  76.5, 102. , 127.5, 153. , 178.5, 204. ,
        229.5, 255. ]))

SUCCESS> D:\datasets\lung\ild\ILD_DB_lungMasksK\101\lung_mask\lung_mask_2_8.dcm --> D:\datasets\lung\ild\ILD_DB_lungMasksKPNG\101\lung_mask\lung_mask_2_8.png


(array([226645,      0,      0,      0,      0,      0,      0,      0,
             0,  35499], dtype=int64),
 array([  0. ,  25.5,  51. ,  76.5, 102. , 127.5, 153. , 178.5, 204. ,
        229.5, 255. ]))

SUCCESS> D:\datasets\lung\ild\ILD_DB_lungMasksK\101\lung_mask\lung_mask_2_9.dcm --> D:\datasets\lung\ild\ILD_DB_lungMasksKPNG\101\lung_mask\lung_mask_2_9.png


In [5]:

def mri_to_png(mri_file, png_file):
    """ Function to convert from a DICOM image to png
        @param mri_file: An opened file like object to read te dicom data
        @param png_file: An opened file like object to write the png data
    """

    # Extracting data from the mri file
    plan = dicom.dcmread(mri_file)
    shape = plan.pixel_array.shape
    img = plan.pixel_array
    threshold = 500 # Adjust as needed
    img_s = np.array((np.maximum(img, 0) / (np.amax(img) + threshold)) * 255.0, dtype=int)
    display(np.histogram(img_s))
    # Writing the PNG file
    print(png_file)
    cv2.imwrite(png_file ,img_s)



In [5]:
# reorganization file system 
# ild files seperate each folder
import os, shutil, glob
import dicom2nifti
import dicom2nifti.settings as settings

def fast_scandir(dirname):
    subfolders    = [f.path for f in os.scandir(dirname) if f.is_dir()]
    for dirname in list(subfolders):
        subfolders.extend(fast_scandir(dirname))
        files    = [g.path for g in os.scandir(dirname) if g.is_file()]
        folders  = [g.path for g in os.scandir(dirname) if g.is_dir()]
        print(dirname +"==>"+ str(len(folders)))  
        if len(folders)!=0 and len(files)>0 :
            target_dir=os.path.join(dirname, "axial")
            if not os.path.exists(target_dir):
                os.makedirs(target_dir)
            for file_name in files:
                if(file_name.endswith('.dcm')):
                    shutil.move(os.path.join(dirname,file_name), target_dir)
    return subfolders

def folder2fname(dirname):
    dnX=dirname.split('\\')
    nameX="parent"+dnX[0]
    for d in range(1,len(dnX)):
        nameX+="_"+dnX[d]
    return nameX

def copyFileNewFolder(path):
    files    = [f.path for f in os.scandir(path) if f.is_file()]
    return files

def scandirDcm2Nifti(source_dir,target_dir):
    subfolders    = [f.path for f in os.scandir(source_dir) if f.is_dir()]
    for dirname in list(subfolders):
        subfolders.extend(scandirDcm2Nifti(dirname,target_dir))
        files    = [g.path for g in os.scandir(dirname) if g.is_file()]
        folders  = [g.path for g in os.scandir(dirname) if g.is_dir()]    
        if len(files)>0:
            original_dicom_directory=dirname
            fname=folder2fname(dirname.replace(root_dir,""))+".nii.gz"
            output_file=os.path.join(target_dir, fname)
            print(fname)
            print(output_file)
            if not os.path.exists(output_file):
                dicom2nifti.dicom_series_to_nifti(original_dicom_directory, output_file, reorient_nifti=True)
    return subfolders

def folder2fname(dirname):
    dnX=dirname.split('\\')
    nameX="parent"+dnX[0]
    for d in range(1,len(dnX)):
        nameX+="_"+dnX[d]
    return nameX

root_dir = 'D:\\datasets\\lung\\ild\\ILD_DB_lungMasksK\\'
target_dir = 'D:\\datasets\\lung\\ild\\ILD_DB_lungMasksKNifti\\'

# fList=fast_scandir(root_dir)
scandirDcm2Nifti(root_dir,target_dir)


# # display(fList)
# fListName=[]
# for dirname in fList:
#     dn=dirname.replace(root_dir, "")
#     dnX=folder2fname(dn)
#     fListName.append(dnX) 


# display(fListName)

    
# file_names = os.listdir(source_dir)
    
# for file_name in file_names:
#     shutil.move(os.path.join(source_dir, file_name), target_dir)

parent101_axial.nii.gz
D:\datasets\lung\ild\ILD_DB_lungMasksKNifti\parent101_axial.nii.gz
parent101_lung_mask.nii.gz
D:\datasets\lung\ild\ILD_DB_lungMasksKNifti\parent101_lung_mask.nii.gz
parent105_axial.nii.gz
D:\datasets\lung\ild\ILD_DB_lungMasksKNifti\parent105_axial.nii.gz
parent105_lung_mask.nii.gz
D:\datasets\lung\ild\ILD_DB_lungMasksKNifti\parent105_lung_mask.nii.gz
parent107_axial.nii.gz
D:\datasets\lung\ild\ILD_DB_lungMasksKNifti\parent107_axial.nii.gz
parent107_lung_mask.nii.gz
D:\datasets\lung\ild\ILD_DB_lungMasksKNifti\parent107_lung_mask.nii.gz
parent108_axial.nii.gz
D:\datasets\lung\ild\ILD_DB_lungMasksKNifti\parent108_axial.nii.gz
parent108_lung_mask.nii.gz
D:\datasets\lung\ild\ILD_DB_lungMasksKNifti\parent108_lung_mask.nii.gz
parent109_axial.nii.gz
D:\datasets\lung\ild\ILD_DB_lungMasksKNifti\parent109_axial.nii.gz
parent109_lung_mask.nii.gz
D:\datasets\lung\ild\ILD_DB_lungMasksKNifti\parent109_lung_mask.nii.gz
parent112_axial.nii.gz
D:\datasets\lung\ild\ILD_DB_lungMasks

parent51_lung_mask.nii.gz
D:\datasets\lung\ild\ILD_DB_lungMasksKNifti\parent51_lung_mask.nii.gz
parent53_CT-INSPIRIUM-1841_axial.nii.gz
D:\datasets\lung\ild\ILD_DB_lungMasksKNifti\parent53_CT-INSPIRIUM-1841_axial.nii.gz
parent53_CT-INSPIRIUM-1841_lung_mask.nii.gz
D:\datasets\lung\ild\ILD_DB_lungMasksKNifti\parent53_CT-INSPIRIUM-1841_lung_mask.nii.gz
parent53_CT-INSPIRIUM-7605_axial.nii.gz
D:\datasets\lung\ild\ILD_DB_lungMasksKNifti\parent53_CT-INSPIRIUM-7605_axial.nii.gz
parent53_CT-INSPIRIUM-7605_lung_mask.nii.gz
D:\datasets\lung\ild\ILD_DB_lungMasksKNifti\parent53_CT-INSPIRIUM-7605_lung_mask.nii.gz
parent56_axial.nii.gz
D:\datasets\lung\ild\ILD_DB_lungMasksKNifti\parent56_axial.nii.gz
parent56_lung_mask.nii.gz
D:\datasets\lung\ild\ILD_DB_lungMasksKNifti\parent56_lung_mask.nii.gz
parent57_CT--0002_axial.nii.gz
D:\datasets\lung\ild\ILD_DB_lungMasksKNifti\parent57_CT--0002_axial.nii.gz
parent57_CT--0002_lung_mask.nii.gz
D:\datasets\lung\ild\ILD_DB_lungMasksKNifti\parent57_CT--0002_lung_

['D:\\datasets\\lung\\ild\\ILD_DB_lungMasksK\\101',
 'D:\\datasets\\lung\\ild\\ILD_DB_lungMasksK\\105',
 'D:\\datasets\\lung\\ild\\ILD_DB_lungMasksK\\107',
 'D:\\datasets\\lung\\ild\\ILD_DB_lungMasksK\\108',
 'D:\\datasets\\lung\\ild\\ILD_DB_lungMasksK\\109',
 'D:\\datasets\\lung\\ild\\ILD_DB_lungMasksK\\112',
 'D:\\datasets\\lung\\ild\\ILD_DB_lungMasksK\\116',
 'D:\\datasets\\lung\\ild\\ILD_DB_lungMasksK\\118',
 'D:\\datasets\\lung\\ild\\ILD_DB_lungMasksK\\119',
 'D:\\datasets\\lung\\ild\\ILD_DB_lungMasksK\\12',
 'D:\\datasets\\lung\\ild\\ILD_DB_lungMasksK\\120',
 'D:\\datasets\\lung\\ild\\ILD_DB_lungMasksK\\121',
 'D:\\datasets\\lung\\ild\\ILD_DB_lungMasksK\\122',
 'D:\\datasets\\lung\\ild\\ILD_DB_lungMasksK\\123',
 'D:\\datasets\\lung\\ild\\ILD_DB_lungMasksK\\124',
 'D:\\datasets\\lung\\ild\\ILD_DB_lungMasksK\\126',
 'D:\\datasets\\lung\\ild\\ILD_DB_lungMasksK\\127',
 'D:\\datasets\\lung\\ild\\ILD_DB_lungMasksK\\129',
 'D:\\datasets\\lung\\ild\\ILD_DB_lungMasksK\\130',
 'D:\\dataset

In [9]:
filepath="D:\\datasets\\lung\\ild\\ILD_DB_lungMasksKNifti\\"
BASE_IMG_PATH=os.path.join('..',filepath)
Target_IMG_PATH="D:\\datasets\\lung\\ild\\ILD_DB_lungMasksKNifti2PNG\\"
print(BASE_IMG_PATH)
print(Target_IMG_PATH)

all_images=sorted(glob(os.path.join(BASE_IMG_PATH,'*axial.nii.gz')))
all_masks =sorted(glob(os.path.join(BASE_IMG_PATH,'*lung_mask.nii.gz')))
i=0
for item in all_images:
    fname=os.path.basename(all_images[i])
    fnameA=fname.split("_")
    test_image=nib.load(all_images[i]).get_fdata()
    test_mask=nib.load(all_masks[i]).get_fdata()
    i=i+1

    r=test_image.shape[2]
    for yy in range(0,r):
        #print(yy)
        img=test_image[:,:,yy]
        img=np.rot90(img)
        img = img.astype(np.uint8)
        imageName='{}{}_slices_{:03}.png'.format(Target_IMG_PATH,fnameA[0], yy)
        imageio.imwrite(imageName, img)
        print(imageName," saved")
        maskImg=test_mask[:,:,yy]
        maskImg=np.rot90(maskImg)*255
        maskImg = maskImg.astype(np.uint8)
        mimageName='{}{}_slices_{:03}.png'.format(Target_IMG_PATH,fnameA[0], yy)
        imageio.imwrite(mimageName, maskImg)
        print(mimageName," saved")
      

D:\datasets\lung\ild\ILD_DB_lungMasksKNifti\
D:\datasets\lung\ild\ILD_DB_lungMasksKNifti2PNG\


TypeError: 'module' object is not callable